# Generated by Django 4.2.3 on 2023-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
    ]
